version: "3"
services:
  app:
    container_name: node_app
    restart: always
    image: narongrit/resturant_api:1.0.0
    ports:
      - "80:3000"
    environment:
      - MONGO_SERVER=mongodb://mongo-db:27017
    depends_on: 
      - mongo-db
  mongo-db:
    container_name: mongo-db
    image: mongo
    volumns:
      - ./mongo_data:/etc/mongo
    restart: always
    ports:
      - "27017:27017"
    
