version: "3"
services:
  app:
    container_name: node_app
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - ./:/home/node/app
    links:
      - mongo-admin
    environment:
      - MONGO_SERVER=mongodb://mongo-db:27017
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  mongo-admin:
    container_name: mongo-admin
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    links:
      - mongo-db:mongo


    
